module(name = "ripgrep_bazel_bench")

bazel_dep(name = "rules_rust", version = "0.74.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.97.1"],
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//crates/globset:Cargo.toml",
        "//crates/grep:Cargo.toml",
        "//crates/cli:Cargo.toml",
        "//crates/index:Cargo.toml",
        "//crates/matcher:Cargo.toml",
        "//crates/pcre2:Cargo.toml",
        "//crates/printer:Cargo.toml",
        "//crates/regex:Cargo.toml",
        "//crates/searcher:Cargo.toml",
        "//crates/ignore:Cargo.toml",
    ],
)
use_repo(crate, "crates")
