load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "globset",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    crate_features = ["default", "log"],
    aliases = aliases(),
    deps = all_crate_deps(normal = True) + [],
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)
